### ISSUE TITLE
Security issue on OSX

### ISSUE THREAD

**Issue by alexarje** [fourMs/VideoAnalysis#10]
When trying to run the install script (at least on OS 10.11), OSX complains about the security settings. Should be documented that the user needs to give run access also to this script. 

![Screen Shot 2020-02-26 at 09 12 35](https://user-images.githubusercontent.com/114316/75335064-24d62800-5889-11ea-89b2-d8170a5202bb.png)

**Comment by aleksati** [comment]
Are you referring to the readme.txt that I should be more specific about this, @alexarje ? I could do that. I could also mention what to add to the terminal if all else fails, like what someone experienced on Mojave 10.14.6.

**Comment by alexarje** [comment]
Yes, that would be great. Just imagine that this should be understandable by a random person that does not know very much about how a computer works...

**Comment by alexarje** [comment]
And, can you also add the script and readme to github? It would also be useful to have a description there describing everything necessary to build the app on the two OSes.

**Comment by aleksati** [comment]
Okay, just added a new and more comprehensive readme to the UiO page .zip and to this FourMS VideoAnalysis repo.
