### ISSUE TITLE
Move mg-preview to somewhere else

### ISSUE THREAD

**Issue by alexarje** [fourMs/VideoAnalysis#11]
I cannot see anything in the preview window (OS10.11). Should there be a motiongram there? 

![Screen Shot 2020-02-26 at 11 18 24](https://user-images.githubusercontent.com/114316/75335524-e9882900-5889-11ea-81f2-5d7382b01a53.png)

**Comment by aleksati** [comment]
Ah, yes @alexarje you just have to click the "Preview" button for it to appear. It's a realtime feature so it clears automatically when exporting.

**Comment by alexarje** [comment]
Ah, I see. I thought it would preview while exporting. It is slightly confusing to have previews both inside of the main window and outside. We should perhaps rethink this design in the next iteration. So I will move it to the next milestone.

**Comment by aleksati** [comment]
There has been some development on this matter, so I am going to make another issue for this.
