### ISSUE TITLE
Basic image pre-processing

### ISSUE THREAD

**Issue by alexarje** [fourMs/VideoAnalysis#12]
One possible further development could be to add some very basic image pre-processing, such as, brightness and contrast adjustments.

**Comment by alexarje** [comment]
You can probably take a look at how this is done in VideoEditor: https://github.com/alexarje/VideoEditor

**Comment by aleksati** [comment]
This is now added to the UI for the VA 2.1. I took out the motiongram preview to make room for this option (saturation, contrast, and brightness) and the future History Video settings mentioned in issue #40 . I remember we planned on moving the mg-preview to the Display (possibly?) anyways.

However, now that we have some color settings in the menubar (grayscale and inverted) and some are in the UI (saturation, contrast, and brightness) I think we should move the Grayscale and Inverted color options down to the UI. That way, we gather all the color options easily in view for the user and spare more unique options for the menubar, like Rotation and various Export settings. 

Any thoughts on this @balintlaczko or @alexarje ?

**Comment by balintlaczko** [comment]
Great! Yes, I agree, let's keep the color stuff together! If we start to get short of screen real-estate we can start implementing a tabbed view (and then even the export options check boxes can make their return in a an "export" tab or something if we want them to), the motiongram previews (horizontal and vertical?) can also be a tab, and so on...

**Comment by aleksati** [comment]
Cool, I´ll close this now and make another issue.
