### ISSUE TITLE
Link to github

### ISSUE THREAD

**Issue by alexarje** [fourMs/VideoAnalysis#14]
I think it would be useful to link to the github page somewhere within the program, so that people can find documentation as well as a pointer to where to submit bugs.

**Comment by aleksati** [comment]
Yes, good point. Maybe we could have a "Report" section in the menubar

**Comment by alexarje** [comment]
Yes, preferably under help, I think.

**Comment by balintlaczko** [comment]
Done! NB. if your _maxinterface.json_ is the default one you won't be able to see this change in the patch, only in the build (and only if you follow the instructions in _build_info/build_checklist.txt_). Alternatively, you can do what I did on my system: swapping the _maxinterface.json_ found at (on Windows) _C:\\Program Files\Cycling'74\Max 8\resources\interfaces\maxinterface.json_. But back up the original one, just in case. That way it will work in the patch too.
Here is how it looks in the build:
![image](https://user-images.githubusercontent.com/45127463/75567686-36b6f700-5a52-11ea-82a2-34011c7c2e64.png)
Upon clicking on this, the default browser opens the Issues page of this repo.
