### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by alexarje** [fourMs/VideoAnalysis#19]
It would be very useful to have the possibility to rotate the video (90, 180, 270) degrees.

**Comment by alexarje** [comment]
You can probably take a look at how this is done in VideoEditor: https://github.com/alexarje/VideoEditor

**Comment by aleksati** [comment]
Added clockwise 90-degree rotations to the VA. I put the option in the menubar under "Image", which now replaces the "Color" tab. The "Image" tab now has inverted, grayscale + rotation options. More on this topic in issue #12 . The rotation values are stored in the settings, and also affects the moviedim of the whole system.
