### ISSUE TITLE
Flickering videos

### ISSUE THREAD

**Issue by alexarje** [fourMs/VideoAnalysis#22]
I just ran a full analysis on all the three videos I have uploaded in the test_videos folder. Most things work well, but I see that all the exported videos behave strangely. On OSX the output videos flicker between green and normal. 

![Screen Shot 2020-02-27 at 11 28 54](https://user-images.githubusercontent.com/114316/75436398-c5dde500-5954-11ea-8fcf-82ddf7806a24.png)

**Comment by alexarje** [comment]
and on Windows I get this type of scrambled video when playing in the media player: 

![Screenshot (3)](https://user-images.githubusercontent.com/114316/75436518-fe7dbe80-5954-11ea-970d-7f9b5a75941e.png)

![Screenshot (2)](https://user-images.githubusercontent.com/114316/75436500-f7ef4700-5954-11ea-86db-652f00953b04.png)

**Comment by alexarje** [comment]
The files play ok in VLC, but still there appears to be something strange with the codec. Perhaps we should just switch to regular .mp4 file output with h264 compression. That is more future-proof than .mov anyways, I think.

**Comment by aleksati** [comment]
Indeed, this is something we also experienced but forgot to make an issue out of.

**Comment by balintlaczko** [comment]
Yes, indeed. Let's switch to .mp4 and h264.

**Comment by aleksati** [comment]
Implemented this now. The flickering is gone. However, it would be nice to do some testing on Windows and other OSes as well before closing this issue.

**Comment by balintlaczko** [comment]
Well done, the gibberish video is indeed gone on Windows too! Good job!
