### ISSUE TITLE
Motion video should always start with an empty frame

### ISSUE THREAD

**Issue by balintlaczko** [fourMs/VideoAnalysis#24]
This is already happening most of the time, but still having a problem occasionally due to #23

**Comment by balintlaczko** [comment]
Phew, this was a hard one. The recently implemented `reset` method for `[mg.motion]` was already ensuring the black first frame (and not an accidental flash of the first frame), but then there were some issues with calling `reset` at the wrong time, and manually banging out movie frames (for some other purpose) in the wrong time. Now it seems to work consistently in all color modes.

**Comment by balintlaczko** [comment]
In batch export, there are still junk first frames in the motion videos every now and then. Works well with single video files, so there has to be some problem during the batch export.

**Comment by balintlaczko** [comment]
Phew again! Now it works in batch export as well. There is a very particular thing with `[jit.op]`. If you want to avoid invalid output, even just a _single_ invalid result, you should make sure that it's planecounts and dims are set **before** you send in the two matrices. Otherwise the first-ever output (after the creation of the object) will always be invalid. Grew some grey hair until I tracked this down...
NB this can actually be a potential problem in other parts of the program too.

**Comment by aleksati** [comment]
Jupp, this still happens occasionally(!). Had to work hard to reproduce it again though, so its as good as done. However, we can keep this open as a reminder (and later development)

**Comment by balintlaczko** [comment]
Another attempt, hopefully this is fixed now. :)
