### ISSUE TITLE
mhi-first and last sometimes render compl. white when first video is inverted.

### ISSUE THREAD

**Issue by aleksati** [fourMs/VideoAnalysis#36]
This tends to happen for me when the first video has an inverted setting and I´m currently on another video in the folder and hit export. Both mhi-first and last can then have these identical outcomes, which is a bit strange. Perhaps some scheduling issues. or something.

![Screen Shot 2020-03-02 at 9 22 32 PM](https://user-images.githubusercontent.com/54307488/75714600-4f324600-5ccc-11ea-8deb-43f4243061fd.png)

**Comment by aleksati** [comment]
This might be fixed now. Haven't been able to reproduced this recently.

**Comment by alexarje** [comment]
Have not been able to reproduce. Closing this now.
