### ISSUE TITLE
Change history video settings

### ISSUE THREAD

**Issue by alexarje** [fourMs/VideoAnalysis#40]
It would be good to have a setting for the motion history video somewhere.

**Comment by aleksati** [comment]
@alexarje , what kind of setting would are you referring to? It would be nice if they corresponded to the other fourMS analysis applications.

**Comment by alexarje** [comment]
I am thinking about having a setting for how long the history should be. I guess frames would be the best unit to measure this in.

**Comment by aleksati** [comment]
I added the option to control the snake length, which effectively is how long the history is, and the snake point size, so the size of the circles drawn. These were already in the application actually, just made them available to the user, a part of the settings dictionary which you can save and/or load, and the log.txt.
