### ISSUE TITLE
Make videogram

### ISSUE THREAD

**Issue by alexarje** [fourMs/VideoAnalysis#44]
It would be great to implement the possibility of creating videograms instead of motiongrams. The only difference is that it is the original (or pre-processed) video that is sent to the motiongram module (instead of the motion image). I have explained the difference here: 
http://www.arj.no/2011/07/13/difference-between-videogram-and-motiongram/

It is a simple fix, mainly a menu item somewhere.

**Comment by aleksati** [comment]
Cool, yes we can make an option to export this as well, in the menubar. Both X and Y?

**Comment by alexarje** [comment]
Yes, please!

**Comment by aleksati** [comment]
This is now implemented.

**Comment by alexarje** [comment]
Nice. But where is it in the menus? Have looked at both the VideoAnalysis version and VideoAnalysis_18.03

**Comment by aleksati** [comment]
Pull again, @alexarje . Should be in the main VideoAnalysis file.

**Comment by aleksati** [comment]
Oh, you are correct I think! there are now two average image selections on my side. Will fix this now

**Comment by aleksati** [comment]
Can you pull and try again now, @alexarje ?

**Comment by alexarje** [comment]
Yes, now it works. Great. But: I see that the exported videos (box, centroid, motion) are now saved as .MOV files. So something must have happened somewhere there.

**Comment by aleksati** [comment]
Ah, okay. I will make another issue just to remember to look into it.
