### ISSUE TITLE
Re-organize and rename

### ISSUE THREAD

**Issue by alexarje** [fourMs/VideoAnalysis#47]
I am preparing a talk in which I am going to show the app, and then I realize that we may want to reorganize the GUI a little to show the workflow: 

1. Add video
2. Pre-process settings 
    a. Crop
    b. Trim
    c. Skip
    c. Color
3. Visualization settings
    a. Motion video (what is now called "Motion image)
    b. Centroid video (what is now called "History image")
    c. Box video (what is now called "Box Image")
4. Export

Perhaps it would make sense to have the main preview window in the middle of the GUI, and have steps 1 and 2 to the left and 3 and 4 to the right? Then there would be a natural flow from top left to bottom right as you select things?

**Comment by aleksati** [comment]
Great. All suggestions are very welcome when it comes to designing the UI.

When are you giving the talk, @alexarje ? The reason I´m asking is that we discussed using tabs in apps interface, for instance, having a motiongram preview with the mg-settings in another tab. Just a portion of the UI.

**Comment by alexarje** [comment]
I will give the talk on Wednesday: https://www.uio.no/ritmo/english/news-and-events/events/seminars/2020/food-and-paper/jensenius/index.html 
But it doesn't have to be finished by then. There I will primarily focus on the different types of visualization, not the app as such.

**Comment by aleksati** [comment]
Now it looks something like this:

![Screen Shot 2020-03-23 at 8 50 21 PM](https://user-images.githubusercontent.com/54307488/77357242-1e33b700-6d48-11ea-9d08-5042d5a94924.png)

![Screen Shot 2020-03-23 at 8 50 44 PM](https://user-images.githubusercontent.com/54307488/77357290-30155a00-6d48-11ea-9872-2957dfde8443.png)

Using tabs for portions of the apps interface also works fine, I think. I'm not super happy with how it looks now, but it´s easy enough to change in any way we like.
